# -*- coding: utf-8 -*-
"""Oil_AI_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NGFPVqwNujXomLSS9OpIDPj4_IzGTq2Y
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from prophet import Prophet
import plotly.graph_objects as go
import gradio as gr
import os

# -----------------------------------------------------------------
# 1. CLEANING FUNCTION FOR YOUR CSVs
# -----------------------------------------------------------------
def clean_weekly_csv(file_path, price_column_name):
    print(f"\nProcessing file: {file_path}")
    if not os.path.exists(file_path):
        print(f"File not found: {file_path}")
        empty_df = pd.DataFrame(columns=['ds', price_column_name])
        empty_df['ds'] = pd.to_datetime(empty_df['ds']) # Ensure datetime dtype
        empty_df[price_column_name] = pd.to_numeric(empty_df[price_column_name]) # Ensure numeric dtype
        return empty_df

    df = pd.read_csv(file_path, encoding='latin1')
    df.columns = df.columns.str.strip()
    df = df.dropna(subset=['Week Of'])

    day_mapping = {
        'Mon': 0, 'Teu': 1, 'wed': 2, 'Wend': 2, 'Thu': 3, 'Fri': 4, 'fri': 4,
        'Tue': 1, 'Wed': 2, 'Thur': 3, 'Tues': 1 # Added more common variations for robustness
    }
    # Normalize DataFrame column names for case-insensitive lookup
    normalized_df_columns = {col.lower(): col for col in df.columns}

    rows = []
    if not df.empty: # Only iterate if df is not empty after initial cleaning
        for idx, row in df.iterrows():
            week_of_val = str(row['Week Of']).replace('\xa0', '').strip()

            # Flexible parsing for 'Week Of' string: if 'to' in week_of_val, split, otherwise use the whole string
            if 'to' in week_of_val:
                week_str = week_of_val.split('to')[0].strip()
            else:
                week_str = week_of_val

            # Debug print: What is the raw week string we are trying to parse?
            print(f"  Row {idx}: Processing 'Week Of': '{week_of_val}' -> parsed week_str: '{week_str}'")

            date_formats_to_try = [
                '%Y %b-%e',  # e.g., 2024 Jan-1
                '%Y %b %d',  # e.g., 2024 Jan 01
                '%Y-%m-%d',  # e.g., 2024-01-01
                '%d/%m/%Y',  # e.g., 01/01/2024
                '%m/%d/%Y',  # e.g., 01/01/2024
                '%Y-%b-%d',  # e.g., 2024-Jan-01
                '%Y-%m-%dT%H:%M:%S', # For ISO format if needed
                '%Y/%m/%d',
                '%b-%e-%Y', # e.g., Jan-1-2024
                '%b %e, %Y' # e.g., Jan 1, 2024
            ]
            base_date = pd.NaT
            for fmt in date_formats_to_try:
                base_date = pd.to_datetime(week_str, format=fmt, errors='coerce')
                if pd.notna(base_date):
                    print(f"    Successfully parsed week_str '{week_str}' with format '{fmt}' to base_date: {base_date}")
                    break

            if pd.isna(base_date):
                print(f"    Trying generic parse for week_str: '{week_str}'")
                base_date = pd.to_datetime(week_str, errors='coerce') # Fallback to generic parser

            if pd.isna(base_date):
                print(f"    Failed to parse base_date for week_str: '{week_str}'. Skipping row.")
                continue # Skip row if date parsing still fails

            for day_col_map, day_offset in day_mapping.items():
                # Find the actual column name in df (case-insensitive match)
                actual_day_col = normalized_df_columns.get(day_col_map.lower())

                if actual_day_col and pd.notna(row[actual_day_col]):
                    val = str(row[actual_day_col]).strip()
                    if val and val != '.' and val != '':
                        try:
                            actual_date = base_date + pd.Timedelta(days=day_offset)
                            rows.append({'ds': actual_date, price_column_name: float(val)})
                            print(f"      Added: ds={actual_date}, {price_column_name}={float(val)}")
                        except ValueError:
                            print(f"      Value error for '{val}' in column '{actual_day_col}'. Skipping.")
                            pass

    # If no rows were successfully extracted, return an empty DataFrame with the expected columns and dtypes
    if not rows:
        print(f"  No data successfully extracted for {file_path}. Returning empty DataFrame.")
        empty_df = pd.DataFrame(columns=['ds', price_column_name])
        empty_df['ds'] = pd.to_datetime(empty_df['ds']) # Ensure datetime dtype
        empty_df[price_column_name] = pd.to_numeric(empty_df[price_column_name]) # Ensure numeric dtype
        return empty_df

    cleaned_df = pd.DataFrame(rows)
    print(f"  Successfully extracted {len(cleaned_df)} rows for {file_path}.")
    return cleaned_df.drop_duplicates(subset=['ds'])

# -----------------------------------------------------------------
# 2. LOAD & PREPARE GLOBAL DATASET FROM DRIVE
# -----------------------------------------------------------------
drive_folder = '/content/drive/MyDrive/Oil_Project/'

wti_path = os.path.join(drive_folder, 'Cushinig ,OKWTI Sopt PRice FOB(Dollar Per Barrel).csv')
brent_eu_path = os.path.join(drive_folder, 'Europe Brent  Spot price FOB(Dollar per Barrel).csv')
brent_sg_path = os.path.join(drive_folder, 'Brent Price-2024.csv')

# Process files
wti_df = clean_weekly_csv(wti_path, 'WTI_Price')
brent_eu_df = clean_weekly_csv(brent_eu_path, 'Brent_Europe_Price')

# Process brent_sg_path using clean_weekly_csv directly
brent_sg_df = clean_weekly_csv(brent_sg_path, 'Brent_Singapore_Price')

# Combined core dataset
merged_df = pd.merge(wti_df, brent_eu_df, on='ds', how='outer')
merged_df = pd.merge(merged_df, brent_sg_df, on='ds', how='outer')
merged_df = merged_df.sort_values('ds').reset_index(drop=True)

# -----------------------------------------------------------------
# 3. INTERACTIVE DASHBOARD CORE LOGIC
# -----------------------------------------------------------------
def generate_forecast_dashboard(market_choice, prediction_days):
    column_map = {
        "US Market (WTI Price)": "WTI_Price",
        "Global Market (Europe Brent)": "Brent_Europe_Price",
        "Asian Market (Singapore Brent)": "Brent_Singapore_Price"
    }

    target_col = column_map[market_choice]
    prophet_df = merged_df[['ds', target_col]].dropna()
    prophet_df.columns = ['ds', 'y']

    if prophet_df.empty:
        return go.Figure().update_layout(title="No data found for this selection.")

    # Train model dynamically
    model = Prophet(daily_seasonality=False, weekly_seasonality=True, yearly_seasonality=False)
    model.fit(prophet_df)

    # Forecast out based on slider selection
    future = model.make_future_dataframe(periods=int(prediction_days), freq='D')
    forecast = model.predict(future)

    # Create interactive Plotly figure
    fig = go.Figure()

    # 1. Shaded Uncertainty Interval
    fig.add_trace(go.Scatter(
        x=pd.concat([forecast['ds'], forecast['ds'].iloc[::-1]]),
        y=pd.concat([forecast['yhat_upper'], forecast['yhat_lower'].iloc[::-1]]),
        fill='toself',
        fillcolor='rgba(0, 123, 255, 0.15)',
        line=dict(color='rgba(255,255,255,0)'),
        hoverinfo="skip",
        name='AI Uncertainty Bounds'
    ))

    # 2. Historical Actual Data Points
    fig.add_trace(go.Scatter(
        x=prophet_df['ds'], y=prophet_df['y'],
        mode='markers',
        marker=dict(color='black', size=4),
        name='Historical Real Price'
    ))

    # 3. AI Target Prediction Trend Line
    fig.add_trace(go.Scatter(
        x=forecast['ds'], y=forecast['yhat'],
        mode='lines',
        line=dict(color='#007bff', width=2),
        name='AI Price Forecast'
    ))

    fig.update_layout(
        title=f"AI Forecast Trend for {market_choice}",
        xaxis_title="Date",
        yaxis_title="Price (USD/BBL)",
        template="plotly_white",
        hovermode="x unified",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1)
    )

    return fig

# -----------------------------------------------------------------
# 4. LAUNCH WEB APP LAYOUT
# -----------------------------------------------------------------
print("🚀 Initializing Dashboard UI...")
app = gr.Interface(
    fn=generate_forecast_dashboard,
    inputs=[
        gr.Dropdown(
            choices=["Global Market (Europe Brent)", "US Market (WTI Price)", "Asian Market (Singapore Brent)"],
            value="Global Market (Europe Brent)",
            label="Select Oil Benchmark Market"
        ),
        gr.Slider(
            minimum=7,
            maximum=90,
            value=30,
            step=1,
            label="Prediction Window (Days into the Future)"
        )
    ],
    outputs=gr.Plot(label="Interactive Forecast Chart"),
    title="🛢️ Interactive AI Oil Price Forecasting Dashboard",
    description="Select an oil benchmark asset and dynamically adjust the machine learning future prediction timelines using Meta Prophet.",
    theme="soft"
)

app.launch(inline=True, debug=True)