# -*- coding: utf-8 -*-
"""oil-price-ai-forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19A5deaiBfZPa5t1NPILfLn1pd-OsJ6V4
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
from prophet import Prophet
import matplotlib.pyplot as plt
import os

# -----------------------------------------------------------------
# 1. HELPER FUNCTION TO CLEAN WEEKLY CSV LAYOUTS
# -----------------------------------------------------------------
def clean_weekly_csv(file_path, price_column_name):
    print(f"\nProcessing file: {os.path.basename(file_path)}")
    # Try different encodings as UnicodeDecodeError often occurs with non-UTF-8 files
    try:
        df = pd.read_csv(file_path, encoding='utf-8')
    except UnicodeDecodeError:
        try:
            df = pd.read_csv(file_path, encoding='latin1')
        except UnicodeDecodeError:
            df = pd.read_csv(file_path, encoding='cp1252') # Fallback to another common encoding
    print(f"Initial DataFrame shape: {df.shape}")

    df.columns = df.columns.str.strip()
    df = df.dropna(subset=['Week Of'])
    print(f"DataFrame shape after dropping NaNs in 'Week Of': {df.shape}")

    df = df[df['Week Of'].str.contains('to', na=False)]
    print(f"DataFrame shape after filtering 'Week Of' with 'to': {df.shape}")

    day_mapping = {
        'Mon': 0, 'Teu': 1, 'wed': 2, 'Wend': 2, 'Thu': 3, 'Fri': 4, 'fri': 4
    }

    rows = []
    for idx, row in df.iterrows():
        # Clean hidden spaces
        week_str = str(row['Week Of']).replace('\xa0', '').split('to')[0].strip()

        # Let pandas infer the date format, as '%e' directive is problematic
        base_date = pd.to_datetime(week_str, errors='coerce')

        if pd.isna(base_date):
            # print(f"Row {idx}: Skipping due to unparsable base_date from '{week_str}'") # Uncomment for detailed debugging
            continue

        # Check if any day columns are present
        found_price_for_row = False
        for col, day_offset in day_mapping.items():
            if col in df.columns and pd.notna(row[col]):
                val = str(row[col]).strip()
                if val and val != '.' and val != '':
                    try:
                        actual_date = base_date + pd.Timedelta(days=day_offset)
                        rows.append({'ds': actual_date, price_column_name: float(val)})
                        found_price_for_row = True
                    except ValueError:
                        # print(f"Row {idx}: Value error for {col} with value '{val}'") # Uncomment for detailed debugging
                        pass
        # if not found_price_for_row:
        #     print(f"Row {idx}: No valid price found for any day column for week_str '{week_str}'. Available columns: {df.columns.tolist()}") # Uncomment for detailed debugging

    cleaned_df = pd.DataFrame(rows).drop_duplicates(subset=['ds'])
    print(f"Final cleaned DataFrame shape for {os.path.basename(file_path)}: {cleaned_df.shape}")
    return cleaned_df

# -----------------------------------------------------------------
# 2. DEFINE GOOGLE DRIVE PATHS
# -----------------------------------------------------------------
drive_folder = '/content/drive/MyDrive/Oil_Project/'

print("🔄 Accessing and cleaning files from your Google Drive 'Oil_Project' folder...")

# List files in the drive folder for debugging
print(f"Files in 'My Drive' root: {os.listdir('/content/drive/MyDrive/')}")

wti_path = os.path.join(drive_folder, 'Cushinig ,OKWTI Sopt PRice FOB(Dollar Per Barrel).csv')
brent_eu_path = os.path.join(drive_folder, 'Europe Brent  Spot price FOB(Dollar per Barrel).csv')
brent_sg_path = os.path.join(drive_folder, 'Brent Price-2024.csv')

# Load and process files
wti_df = clean_weekly_csv(wti_path, 'WTI_Price')
brent_eu_df = clean_weekly_csv(brent_eu_path, 'Brent_Europe_Price')

print(f"\nProcessing Brent Singapore file: {os.path.basename(brent_sg_path)}")
brent_sg_raw = pd.read_csv(brent_sg_path)
print(f"brent_sg_raw after read_csv - Shape: {brent_sg_raw.shape}, Head:\n{brent_sg_raw.head()}")
brent_sg_raw.columns = brent_sg_raw.columns.str.strip()
print(f"brent_sg_raw after column strip - Shape: {brent_sg_raw.shape}, Head:\n{brent_sg_raw.head()}")

# Removed the brent_sg_raw.dropna() call as it was making the DataFrame empty.
# Instead, we create brent_sg_df by directly selecting columns and then dropping NaNs from those.
brent_sg_df = pd.DataFrame({
    'ds': pd.to_datetime(brent_sg_raw.iloc[:, 0], errors='coerce'),
    'Brent_Singapore_Price': pd.to_numeric(brent_sg_raw.iloc[:, 1], errors='coerce')
}).dropna() # Drop NaNs after conversion to ensure valid date and price
print(f"brent_sg_df after final cleaning - Shape: {brent_sg_df.shape}, Head:\n{brent_sg_df.head()}")

# Combine datasets
merged_df = pd.merge(wti_df, brent_eu_df, on='ds', how='outer')
merged_df = pd.merge(merged_df, brent_sg_df, on='ds', how='outer')
merged_df = merged_df.sort_values('ds').reset_index(drop=True)

print(f"✅ Data fully merged! Total trading dates found: {len(merged_df)}")

# -----------------------------------------------------------------
# 3. TRAIN PROPHET AI
# -----------------------------------------------------------------
target_variable = 'Brent_Europe_Price'
prophet_df = merged_df[['ds', target_variable]].dropna()
prophet_df.columns = ['ds', 'y']

print(f"\n🧠 Training Meta Prophet Model on: {target_variable}...")
model = Prophet(daily_seasonality=False, weekly_seasonality=True, yearly_seasonality=False)
model.fit(prophet_df)

# -----------------------------------------------------------------
# 4. FORECAST THE FUTURE (30 Days Out)
# -----------------------------------------------------------------
future = model.make_future_dataframe(periods=30, freq='D')
forecast = model.predict(future)

# -----------------------------------------------------------------
# 5. SAVE FORECAST BACK TO GOOGLE DRIVE
# -----------------------------------------------------------------
future_predictions = forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail(30)
future_predictions.columns = ['Predicted Date', 'Predicted Price', 'Minimum Expected', 'Maximum Expected']

output_file = os.path.join(drive_folder, 'Oil_Price_Predictions_Output.csv')
future_predictions.to_csv(output_file, index=False)
print(f"🎉 SUCCESS! Predictions spreadsheet saved directly to your Drive folder as:\n➡️ '{output_file}'")

# -----------------------------------------------------------------
# 6. DISPLAY CHART
# -----------------------------------------------------------------
model.plot(forecast)
plt.title(f"Prophet AI Prediction for {target_variable}", fontsize=14, fontweight='bold')
plt.xlabel("Date")
plt.ylabel("Price (USD/BBL")
plt.grid(True, alpha=0.3)
plt.show()